name: noa
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch        
  - torchvision   
  - numpy=1.23
  - pandas
  - matplotlib
  - scikit-learn
  - pip

  - pip:
      - requests
      - huggingface-hub
      - pyyaml
      - transformers
      - accelerate
      - git+https://github.com/ggerganov/llama.cpp.git