name: noa
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch        # le vrai package conda pour torch
  - torchvision    # utile pour PyTorch (optionnel)
  - numpy=1.23
  - pandas
  - matplotlib
  - scikit-learn
  - pip

  - pip:
      - requests
      - huggingface-hub
      - pyyaml
      - transformers
      - accelerate
